scene:
  name: Test Scene
  camera:
    position: [0.0, 25.0, 80.0]
    forward: [0.0, 0.0, -1.0]
    up: [0.0, 1.0, 0.0]
    fov: 45.0
    nearPlane: 0.1
    farPlane: 150.0
  objects:
    # Ground platform
    - name: Platform
      position: [0.0, -0.5, 0.0]
      rotationAxis: [0.0, 0.0, 1.0]
      rotationDeg: 0.0
      scale: [20.0, 0.5, 20.0]
      shader: platform
      mesh: cube
      texture: ""
      isStatic: true

    # dirt block
    - name: Block
      position: [0.0, 15.0, 0.0]
      rotationAxis: [0.0, 1.0, 1.0]
      rotationDeg: 45.0
      scale: [1.0, 1.0, 1.0]
      shader: dirtblock
      mesh: cube
      texture: dirtblock
      isStatic: false

    # Sphere
    - name: Sphere
      position: [10.0, 15.0, 0.0]
      rotationAxis: [0.0, 1.0, 1.0]
      rotationDeg: 45.0
      scale: [2.0, 2.0, 2.0]
      shader: sphere
      mesh: sphere
      texture: ""
      isStatic: false